server:
  port: 9060
spring:
  application:
    name: auth
  redis:
    host: 112.74.57.253
    port: 6379
    password: syunredis
  datasource:
    url: jdbc:mysql://112.74.57.253:3306/auth
    username: root
    password: 594682797
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 5
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/