spring:
  application:
    name: gateway
server:
  port: 8080
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
zuul:
  add-proxy-headers: true
  routes:
    auth:
      path: /auth/**
      strip-prefix: false
      sensitiveHeaders:
#        referer,origin,x-forwarded-host,x-forwarded-proto,x-forwarded-port,x-forwarded-for
      serviceId: auth
    resoure:
      path: /resource/**
      strip-prefix: true
      sensitiveHeaders:
      serviceId: resource
#    oauth:
#      path: /auth/**
#      strip-prefix: true
#      sensitiveHeaders:
#      serviceId: authCenter
#security:
#  oauth2:
#    resource:
#      user-info-uri:  http://localhost:9060/user
#      prefer-token-info: false